package dbutils

const train = `
   CREATE TABLE IF NOT EXISTS TRAIN (
      ID INTEGER PRIMARY KEY AUTOINCREMENT,
      DRIVER_NAME VARCHAR(64) NULL,
      OPERATING_STATUS BOOLEAN
   )
`

const station = `
   CREATE TABLE IF NOT EXISTS STATION (
      ID INTEGER PRIMARY KEY AUTOINCREMENT, 
      NAME VARCHAR(64) NULL,
      OPENING_TIME TIME NULL,
      CLOSING_TIME TIME NULL
   )
`

const schedule = `
   CREATE TABLE IF NOT EXISTS SCHEDULE (
      ID INTEGER PRIMARY KEY AUTOINCREMENT, 
      TRAIN_ID INT,
      STATION_ID INT,
      ARRIVAL_TIME TIME,
      FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN(ID),
      FOREIGN KEY (STATION_ID) REFERENCES STATION(ID)
   )
`
