package dbutils

const train = `
   CREATE TABLE IF NOT EXISTS TRAIN (
      ID INTEGER PRIMARY KEY AUTOINCREMENT,
      DRIVER_NAME VARCHAR(64) NULL,
      OPERATING_STATUS BOOLEAN
   )
`

const station = `
   CREATE TABLE IF NOT EXISTS STATION (
      ID INTEGER PRIMARY KEY AUTOINCREMENT, 
      NAME VARCHAR(64) NULL,
      OPENING_TIME TIME NULL,
      CLOSING_TIME TIME NULL
   )
`
